version: 2.1
jobs:
  modmail:
    docker:
      # replace with your preferred image
      - image: cimg/python
    steps:
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose up -d
workflows:
  main-workflow:
    jobs:
      - modmail